name: Laravel Staging Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
      with:
        php-version: '7.4'
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader --no-dev
    - name: Generate app caches
      run: php artisan config:cache && php artisan route:cache && php artisan view:cache
    - name: Write .env file
      run: |
        echo -e 'APP_NAME="Webulan"' > .env
        echo -e 'APP_ENV=production' >> .env
        echo -e 'APP_KEY='${{ secrets.APP_KEY }} >> .env
        echo -e 'APP_DEBUG=false' >> .env
        echo -e 'LOG_CHANNEL=daily' >> .env
        echo -e 'DB_CONNECTION=mysql' >> .env
        echo -e 'DB_HOST=localhost' >> .env
        echo -e 'DB_PORT=${{ secrets.DB_PORT }}' >> .env
        echo -e 'DB_DATABASE=${{ secrets.DB_DATABASE }}' >> .env
        echo -e 'DB_USERNAME=${{ secrets.DB_USERNAME }}' >> .env
        echo -e 'DB_PASSWORD=${{ secrets.DB_PASSWORD }}' >> .env
        echo -e 'BROADCAST_DRIVER=log' >> .env
        echo -e 'CACHE_DRIVER=file' >> .env
        echo -e 'QUEUE_CONNECTION=sync' >> .env
        echo -e 'SESSION_DRIVER=file' >> .env
        echo -e 'SESSION_LIFETIME=120' >> .env
    - name: Install Rsync
      run: sudo apt update && sudo apt install rsync
    - name: Create rsync exclude.txt
      run: |
        echo -e '.git' >> exclude-list.txt
        echo -e '.env.example' >> exclude-list.txt
        echo -e '.gitattributes' >> exclude-list.txt
        echo -e '.gitignore' >> exclude-list.txt
        echo -e '.styleci.yml' >> exclude-list.txt
        echo -e '_ide_helper.php' >> exclude-list.txt
        echo -e '.idea' >> exclude-list.txt
        echo -e '.env.example' >> exclude-list.txt
        echo -e 'test' >> exclude-list.txt
        echo -e 'phpunit.xml' >> exclude-list.txt
        echo -e '.editorconfig' >> exclude-list.txt
        echo -e 'database' >> exclude-list.txt
        echo -e 'tests' >> exclude-list.txt
        echo -e 'README.md' >> exclude-list.txt
        echo -e 'exclude-list.txt' >> exclude-list.txt
    - name: Adding Host key to know_hosts file
      run: mkdir -p ~/.ssh && ssh-keyscan -H ${{ secrets.SERVER_HOSTNAME }} >> ~/.ssh/known_hosts
    - name: Deploy to staging Server via Rsync
      uses: AEnterprise/rsync-deploy@v1.0
      env:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-azvW --delete --exclude-from exclude-list.txt"
          SERVER_PORT: ${{ secrets.SSH_PORT }}
          FOLDER: "./"
          SERVER_IP: ${{ secrets.SERVER_HOSTNAME }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          SERVER_DESTINATION: ${{ secrets.DEPLOY_PATH }}
    - name: Run Script over SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOSTNAME }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: ./tidy-permission.sh
          
